export const METRO_AREAS = [
  { slug: 'paris', name: 'Paris', metroPopulation: 2100600, coreCityName: 'Paris', departmentCode: '75' },
  { slug: 'aix-marseille', name: 'Aix-Marseille', metroPopulation: 1760000, coreCityName: 'Marseille', departmentCode: '13' },
  { slug: 'lyon', name: 'Lyon', metroPopulation: 1700000, coreCityName: 'Lyon', departmentCode: '69' },
  { slug: 'toulouse', name: 'Toulouse', metroPopulation: 1110000, coreCityName: 'Toulouse', departmentCode: '31' },
  { slug: 'lille', name: 'Lille', metroPopulation: 1080000, coreCityName: 'Lille', departmentCode: '59' },
  { slug: 'bordeaux', name: 'Bordeaux', metroPopulation: 1010000, coreCityName: 'Bordeaux', departmentCode: '33' },
  { slug: 'nice', name: 'Nice', metroPopulation: 1000000, coreCityName: 'Nice', departmentCode: '06' },
  { slug: 'strasbourg', name: 'Strasbourg', metroPopulation: 860000, coreCityName: 'Strasbourg', departmentCode: '67' },
  { slug: 'rennes', name: 'Rennes', metroPopulation: 780000, coreCityName: 'Rennes', departmentCode: '35' },
  { slug: 'montpellier', name: 'Montpellier', metroPopulation: 720000, coreCityName: 'Montpellier', departmentCode: '34' },
  { slug: 'nantes', name: 'Nantes', metroPopulation: 710000, coreCityName: 'Nantes', departmentCode: '44' },
  { slug: 'toulon', name: 'Toulon', metroPopulation: 610000, coreCityName: 'Toulon', departmentCode: '83' },
  { slug: 'douai-lens', name: 'Douai-Lens', metroPopulation: 550000, coreCityName: 'Douai', departmentCode: '59' },
  { slug: 'saint-etienne', name: 'Saint-Étienne', metroPopulation: 530000, coreCityName: 'Saint-Étienne', departmentCode: '42' },
  { slug: 'grenoble', name: 'Grenoble', metroPopulation: 520000, coreCityName: 'Grenoble', departmentCode: '38' },
  { slug: 'rouen', name: 'Rouen', metroPopulation: 500000, coreCityName: 'Rouen', departmentCode: '76' },
  { slug: 'tours', name: 'Tours', metroPopulation: 500000, coreCityName: 'Tours', departmentCode: '37' },
  { slug: 'clermont-ferrand', name: 'Clermont-Ferrand', metroPopulation: 490000, coreCityName: 'Clermont-Ferrand', departmentCode: '63' },
  { slug: 'avignon', name: 'Avignon', metroPopulation: 470000, coreCityName: 'Avignon', departmentCode: '84' },
  { slug: 'orleans', name: 'Orléans', metroPopulation: 460000, coreCityName: 'Orléans', departmentCode: '45' },
  { slug: 'angers', name: 'Angers', metroPopulation: 440000, coreCityName: 'Angers', departmentCode: '49' },
  { slug: 'caen', name: 'Caen', metroPopulation: 430000, coreCityName: 'Caen', departmentCode: '14' },
  { slug: 'nancy', name: 'Nancy', metroPopulation: 430000, coreCityName: 'Nancy', departmentCode: '54' },
  { slug: 'dijon', name: 'Dijon', metroPopulation: 390000, coreCityName: 'Dijon', departmentCode: '21' },
  { slug: 'metz', name: 'Metz', metroPopulation: 390000, coreCityName: 'Metz', departmentCode: '57' },
  { slug: 'le-havre', name: 'Le Havre', metroPopulation: 370000, coreCityName: 'Le Havre', departmentCode: '76' },
  { slug: 'valenciennes', name: 'Valenciennes', metroPopulation: 360000, coreCityName: 'Valenciennes', departmentCode: '59' },
  { slug: 'brest', name: 'Brest', metroPopulation: 330000, coreCityName: 'Brest', departmentCode: '29' },
  { slug: 'perpignan', name: 'Perpignan', metroPopulation: 330000, coreCityName: 'Perpignan', departmentCode: '66' },
  { slug: 'reims', name: 'Reims', metroPopulation: 320000, coreCityName: 'Reims', departmentCode: '51' },
  { slug: 'nimes', name: 'Nîmes', metroPopulation: 310000, coreCityName: 'Nîmes', departmentCode: '30' },
  { slug: 'amiens', name: 'Amiens', metroPopulation: 300000, coreCityName: 'Amiens', departmentCode: '80' },
  { slug: 'bayonne', name: 'Bayonne', metroPopulation: 300000, coreCityName: 'Bayonne', departmentCode: '64' },
  { slug: 'annecy', name: 'Annecy', metroPopulation: 290000, coreCityName: 'Annecy', departmentCode: '74' },
  { slug: 'mulhouse', name: 'Mulhouse', metroPopulation: 280000, coreCityName: 'Mulhouse', departmentCode: '68' },
  { slug: 'besancon', name: 'Besançon', metroPopulation: 280000, coreCityName: 'Besançon', departmentCode: '25' },
  { slug: 'frejus-saint-raphael', name: 'Fréjus-Saint-Raphaël', metroPopulation: 280000, coreCityName: 'Fréjus', departmentCode: '83' },
  { slug: 'chambery', name: 'Chambéry', metroPopulation: 270000, coreCityName: 'Chambéry', departmentCode: '73' },
  { slug: 'le-mans', name: 'Le Mans', metroPopulation: 270000, coreCityName: 'Le Mans', departmentCode: '72' },
  { slug: 'saint-nazaire', name: 'Saint-Nazaire', metroPopulation: 260000, coreCityName: 'Saint-Nazaire', departmentCode: '44' },
  { slug: 'poitiers', name: 'Poitiers', metroPopulation: 260000, coreCityName: 'Poitiers', departmentCode: '86' },
  { slug: 'limoges', name: 'Limoges', metroPopulation: 250000, coreCityName: 'Limoges', departmentCode: '87' },
  { slug: 'dunkerque', name: 'Dunkerque', metroPopulation: 250000, coreCityName: 'Dunkerque', departmentCode: '59' },
  { slug: 'la-rochelle', name: 'La Rochelle', metroPopulation: 220000, coreCityName: 'La Rochelle', departmentCode: '17' },
  { slug: 'lorient', name: 'Lorient', metroPopulation: 220000, coreCityName: 'Lorient', departmentCode: '56' },
  { slug: 'vannes', name: 'Vannes', metroPopulation: 210000, coreCityName: 'Vannes', departmentCode: '56' },
  { slug: 'pau', name: 'Pau', metroPopulation: 200000, coreCityName: 'Pau', departmentCode: '64' },
  { slug: 'valence', name: 'Valence', metroPopulation: 200000, coreCityName: 'Valence', departmentCode: '26' },
  { slug: 'troyes', name: 'Troyes', metroPopulation: 180000, coreCityName: 'Troyes', departmentCode: '10' },
  { slug: 'narbonne', name: 'Narbonne', metroPopulation: 170000, coreCityName: 'Narbonne', departmentCode: '11' },
  { slug: 'calais', name: 'Calais', metroPopulation: 160000, coreCityName: 'Calais', departmentCode: '62' },
  { slug: 'niort', name: 'Niort', metroPopulation: 160000, coreCityName: 'Niort', departmentCode: '79' },
  { slug: 'thionville', name: 'Thionville', metroPopulation: 160000, coreCityName: 'Thionville', departmentCode: '57' },
  { slug: 'quimper', name: 'Quimper', metroPopulation: 150000, coreCityName: 'Quimper', departmentCode: '29' },
  { slug: 'montauban', name: 'Montauban', metroPopulation: 150000, coreCityName: 'Montauban', departmentCode: '82' },
  { slug: 'cherbourg', name: 'Cherbourg', metroPopulation: 150000, coreCityName: 'Cherbourg-en-Cotentin', departmentCode: '50' },
  { slug: 'beauvais', name: 'Beauvais', metroPopulation: 140000, coreCityName: 'Beauvais', departmentCode: '60' },
  { slug: 'colmar', name: 'Colmar', metroPopulation: 140000, coreCityName: 'Colmar', departmentCode: '68' },
  { slug: 'angouleme', name: 'Angouleme', metroPopulation: 140000, coreCityName: 'Angouleme', departmentCode: '16' },
  { slug: 'albi', name: 'Albi', metroPopulation: 130000, coreCityName: 'Albi', departmentCode: '81' },
  { slug: 'cholet', name: 'Cholet', metroPopulation: 130000, coreCityName: 'Cholet', departmentCode: '49' },
  { slug: 'laval', name: 'Laval', metroPopulation: 130000, coreCityName: 'Laval', departmentCode: '53' },
  { slug: 'chalon-sur-saone', name: 'Chalon-sur-Saone', metroPopulation: 130000, coreCityName: 'Chalon-sur-Saone', departmentCode: '71' },
  { slug: 'bourg-en-bresse', name: 'Bourg-en-Bresse', metroPopulation: 130000, coreCityName: 'Bourg-en-Bresse', departmentCode: '01' },
  { slug: 'bourges', name: 'Bourges', metroPopulation: 120000, coreCityName: 'Bourges', departmentCode: '18' },
  { slug: 'agen', name: 'Agen', metroPopulation: 120000, coreCityName: 'Agen', departmentCode: '47' },
  { slug: 'tarbes', name: 'Tarbes', metroPopulation: 120000, coreCityName: 'Tarbes', departmentCode: '65' },
  { slug: 'sete', name: 'Sète', metroPopulation: 120000, coreCityName: 'Sète', departmentCode: '34' }
];

export const SOURCE_PERIOD = {
  startYear: 2015,
  endYear: 2024
};
